# Generated by Django 2.0.4 on 2018-05-02 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhotoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(verbose_name="Photo's owner id")),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime when photo was added')),
                ('user_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name="Photo's tags added by user")),
                ('ai_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name="Photo's tags automatically added by Artificial Intelligence")),
                ('downloads', models.PositiveIntegerField(blank=True, default=0, verbose_name='Downloads of the photo')),
            ],
        ),
    ]
